const express = require('express')
const router = express.Router()
const registerRouter = require('./register.router')
const loginRouter = require('./login.router')
const moviesRouter = require('./movies.router')
const resetPassword = require('./resetPassword.router')
router.use('/register', registerRouter)
router.use('/login', loginRouter)
router.use('/movies', moviesRouter)
router.use('/reset-password',resetPassword)
module.exports = router